osx_image: xcode9
language: objective-c
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - gem install cocoapods --pre
  - xcrun simctl list
install:
  - ./install_swiftlint.sh
env:
  - MODE=framework
  - MODE=examples
script: 
  - swiftlint
  - ./build.sh $MODE

# whitelist
branches:
  only:
    - master
